language: bash
os:
  - linux
  - osx
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ksh zsh
script:
  - bash clitest dev/test.md
  - ksh  clitest dev/test.md
  - zsh  clitest dev/test.md
  - sh   clitest dev/test.md
notifications:
  email: false
