language: bash
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - ksh
      - zsh
script:
  - bash clitest test.md
  - ksh  clitest test.md
  - zsh  clitest test.md
  - sh   clitest test.md
notifications:
  email: false
