# clitest-dev
# Local Docker image used for clitest development.
#
# It has all the required tools for linting and testing clitest code.
# See Makefile for commands to build and run this image.
#
# If you're searching for the official clitest Docker image (for users):
# https://hub.docker.com/r/aureliojargas/clitest

FROM alpine:3.18

# Perl is required by clitest's --regex matching mode
RUN apk --no-cache add \
    bash dash mksh zsh \
    perl \
    make \
    checkbashisms shellcheck shfmt

WORKDIR /mnt
