# https://docs.github.com/en/actions/reference

name: Check
on:
  push:
  pull_request:
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: make docker-build
      - run: make lint
      - run: make validate-docs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: make docker-build
      - run: make versions
      - run: make test

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./
        with:
          files: examples/cut.txt examples/hello-world.txt
          options: --first --progress none
