# https://docs.github.com/en/actions/reference

name: Check
on:
  push:
  pull_request:
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make docker-build
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make docker-build
      - run: make versions
      - run: make test
